import java.util.Random;
/**
 *  Computes some statistics about families in which the parents decide 
 *  to have children until they have at least one child of each gender.
 *  The program expects to get two command-line arguments: an int value
 * 	that determines how many families to simulate, and an int value
 *  that serves as the seed of the random numbers generated by the program.
 *  Example usage: % java OneOfEachStats 1000 1
 */
public class OneOfEachStats {
	public static void main (String[] args) {
		// Gets the two command-line arguments

		// Initailizes a random numbers generator with the given seed value
 
		
		int T = Integer.parseInt(args[0]);
		int seed = Integer.parseInt(args[1]);

		Random Generator = new Random(seed);

		int b = 0;
		int g = 0;
		double total = 0; //will receive total num of children from all iterations

		boolean boy = false;
		boolean girl = false; 
		double rnd = 0;
		int count2 = 0;
		int count3 = 0;
		int count4ormore = 0;
		String common = "";

		for (int i = 0; i < T; i++){

			while (boy == false || girl == false){

				rnd = Generator.nextDouble(); //This statement will generate a random value in the range [0,1)
			
				
				
				if (rnd > 0.5){
					girl = true;
					g = g + 1;
				}
				else{
					boy = true;
					b = b + 1;

				}
			}
			if (b + g == 2){
				count2 ++;;
			} 
			else if (b + g == 3){
				count3 ++;
			}
			else{
				count4ormore ++;
			}
			total = total + g + b;  //add children received in last 
			g = 0;  //clean g for next iteration
			b = 0; //clean g for next iteration
			girl = false;
			boy = false;
			}
			
		
		if ((count2 > count3) && (count2 > count4ormore)) common = "2."; //most common is 2 families
		else if ((count3 > count2) && (count3 > count4ormore)) common = "3." ; //most common is 3 families
		else common = "4 or more."; //most common is 4 or more families

		double avg = (double)(total) / T; // total children divised by number of iterations
		
		System.out.println("Average: " + avg + " children to get at least one of each gender.");
		System.out.println("Number of families with 2 children: " + count2);
		System.out.println("Number of families with 3 children: " + count3);
		System.out.println("Number of families with 4 or more children: " + count4ormore);
		System.out.println("The most common number of children is " + common );
	}
	
}

